--drop table PRODUCTOS;

CREATE TABLE PRODUCTOS (
CODIGO_PRODUCTO INT PRIMARY KEY IDENTITY,
DESC_PRODUCTO VARCHAR(250)
);
--drop table DEPARTAMENTO;

CREATE TABLE DEPARTAMENTO (
CODIGO_DPTO INT PRIMARY KEY IDENTITY,
DESCRIPCION_DPTO VARCHAR(250)
);
--drop table CIUDAD;

CREATE TABLE CIUDAD (
COD_CIUDAD INT PRIMARY KEY IDENTITY,
CODIGO_DPTO INT FOREIGN KEY REFERENCES DEPARTAMENTO(CODIGO_DPTO),
DESCRIPCION_CIUDAD VARCHAR(250)
);
--drop table USUARIOS;

CREATE TABLE USUARIOS (
CODIGO_USUARIO INT PRIMARY KEY IDENTITY,
USUARIO VARCHAR(25),
CLAVE VARCHAR(25)
);
--drop table CLIENTES;

CREATE TABLE CLIENTES (
ID_CLIENTE INT PRIMARY KEY IDENTITY,
TIPO_IDENTIFICACION VARCHAR(25),
NUMERO_IDENTIFICACION VARCHAR(25),
NOMBRES VARCHAR(25),
APELLIDOS VARCHAR(25),
CARGO VARCHAR(25),
MAIL VARCHAR(25),
DIRECCION VARCHAR(25),
TELEFONO VARCHAR(25),
CODIGO_CIUDAD INT FOREIGN KEY REFERENCES CIUDAD(COD_CIUDAD),
CODIGO_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(CODIGO_USUARIO),
);
--drop table VENTAS;

CREATE TABLE VENTAS (
ID_VENTA INT PRIMARY KEY IDENTITY,
ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTES(ID_CLIENTE),
CODIGO_CIUDAD INT FOREIGN KEY REFERENCES CIUDAD(COD_CIUDAD),
CODIGO_PRODUCTO INT FOREIGN KEY REFERENCES PRODUCTOS(CODIGO_PRODUCTO),
FECHA_VENTA DATETIME,
VALOR_VENTA DECIMAL,
CANTIDAD_PRODUCTO INT
);

--a.	INSERTAR al menos UN (01) registro cada una de las seis (06) tablas mencionadas

INSERT INTO PRODUCTOS (DESC_PRODUCTO) VALUES('Camisas');
INSERT INTO DEPARTAMENTO(DESCRIPCION_DPTO) VALUES('Cundinamarca');
INSERT INTO CIUDAD(DESCRIPCION_CIUDAD,CODIGO_DPTO) VALUES('Bogota',1);
INSERT INTO USUARIOS(USUARIO,CLAVE) VALUES('hector','147258');
INSERT INTO CLIENTES(TIPO_IDENTIFICACION,NUMERO_IDENTIFICACION,NOMBRES,APELLIDOS,CARGO,MAIL,DIRECCION,TELEFONO,CODIGO_CIUDAD,CODIGO_USUARIO) 
VALUES('Cedula de ciudadania','1049655475','Hector','Cruz','Administrador Ventas','hcruz5785@gmail.com','kr 109 A # 151-09','3219856584',1,1);
INSERT INTO VENTAS(ID_CLIENTE,CODIGO_PRODUCTO,FECHA_VENTA,VALOR_VENTA,CANTIDAD_PRODUCTO) 
VALUES(1,1,'2023/05/06',10000,1);

--b.	CONSULTAR el cliente con TIPO DE IDENTIFICACION =  “CEDULA DE CIUDADANIA” y NÚMERO  DE IDENTIFICACIÓN = “123456789”, presentando como resultado los siguientes campos:

SELECT CL.ID_CLIENTE,CL.NOMBRES,CL.APELLIDOS,CL.DIRECCION,CIU.DESCRIPCION_CIUDAD AS 'DESCRIPCION DE LA CIUDAD',US.USUARIO AS 'NOMBRE DEL USUARIO'
FROM CLIENTES CL
INNER JOIN CIUDAD CIU ON(CIU.COD_CIUDAD = CL.CODIGO_CIUDAD)
INNER JOIN USUARIOS US ON(US.CODIGO_USUARIO = CL.CODIGO_USUARIO)
WHERE CL.TIPO_IDENTIFICACION ='CEDULA DE CIUDADANIA'
AND CL.NUMERO_IDENTIFICACION ='123456789';

--c.	CONSULTAR  la cantidad (total) de clientes con ventas superiores a $30.000.000. Recuerde que el resultado es solo un número 

SELECT COUNT(C.ID_CLIENTE) AS TOTAL FROM CLIENTES C 
INNER JOIN VENTAS V ON(V.ID_CLIENTE = C.ID_CLIENTE)
HAVING SUM(V.VALOR_VENTA) >30000000

--d.	GENERAR un listado de clientes cuyas ventas se hayan realizado entre 01/10/2010 al 31/12/2010. Presentando los siguientes campos:

SELECT CL.ID_CLIENTE,CL.NOMBRES AS 'NOMBRE CLIENTE',CL.APELLIDOS AS 'APELLIDO CLIENTE', V.FECHA_VENTA AS 'FECHA DE LA VENTA', P.DESC_PRODUCTO AS 'DESCRIPCION DEL PRODUCTO',V.VALOR_VENTA AS 'VALOR DE LA VENTA'
FROM CLIENTES CL
INNER JOIN VENTAS V ON(V.ID_CLIENTE = CL.ID_CLIENTE)
INNER JOIN PRODUCTOS p ON(P.CODIGO_PRODUCTO = V.CODIGO_PRODUCTO)
WHERE V.FECHA_VENTA BETWEEN '01/10/2010' AND '31/12/2010'

--•	MODIFICAR la tabla CLIENTES adicionando una columna denominada “CLASE” y asignarle los siguientes valores
--“ALTO” a los clientes cuyas ventas sean superior o igual a 200.000
--“MEDIO” a los clientes cuyas ventas sean superior o igual 100.000 e inferior a 200.000
--“BAJO” a los clientes cuyas ventas sean inferiores a  100.000

ALTER TABLE CLIENTES
ADD CLASE varchar(25);

--Actualizar data

SELECT * FROM CLIENTES;

UPDATE CLIENTES SET CLASE = 'ALTO'
WHERE CLASE IN (SELECT SUM(VALOR_VENTA)FROM VENTAS HAVING SUM(VALOR_VENTA) >= 200000);

UPDATE CLIENTES SET CLASE = 'MEDIO'
WHERE CLASE IN (SELECT SUM(VALOR_VENTA)FROM VENTAS HAVING SUM(VALOR_VENTA) >= 100000 AND SUM(VALOR_VENTA) >200000);

UPDATE CLIENTES SET CLASE = 'BAJO'
WHERE CLASE IN (SELECT SUM(VALOR_VENTA)FROM VENTAS HAVING SUM(VALOR_VENTA) <= 90000);

--•	ELIMINAR de la tabla CLIENTES, los clientes que estén clasificados en la columna “CLASE” con valor “BAJO” . (Tener en cuenta la integridad referencial.)

DELETE FROM CLIENTES WHERE CLASE ='BAJO' 